version: 0.2

phases:
  install:
    runtime-versions:
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - tsc

artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - app.js
    - dist/**/*
    - node_modules/**/*
